### ISSUE TITLE
nans

### ISSUE THREAD

**Issue by shinydinosaur** [caogang/wgan-gp#12]
When I run gan_toy.py I get nans for the discriminator cost, generator cost and wasserstein distance:

iter 99 tmp/8gaussians/disc cost        nan     tmp/8gaussians/gen cost nan     tmp/8gaussians/wasserstein distance     nan
/home/eecs/shiry/anaconda2/lib/python2.7/site-packages/matplotlib/contour.py:1514: UserWarning: Warning: converting a masked element to nan.
  self.zmax = float(z.max())
/home/eecs/shiry/anaconda2/lib/python2.7/site-packages/matplotlib/contour.py:1515: UserWarning: Warning: converting a masked element to nan.
  self.zmin = float(z.min())
/home/eecs/shiry/anaconda2/lib/python2.7/site-packages/matplotlib/contour.py:1153: RuntimeWarning: invalid value encountered in greater
  return lev[(lev > zmin) & (lev < zmax)]
/home/eecs/shiry/anaconda2/lib/python2.7/site-packages/matplotlib/contour.py:1153: RuntimeWarning: invalid value encountered in less
  return lev[(lev > zmin) & (lev < zmax)]
Traceback (most recent call last):
  File "gan_toy.py", line 308, in <module>
    generate_image(_data)
  File "gan_toy.py", line 123, in generate_image
    plt.contour(x, y, disc_map.reshape((len(x), len(y))).transpose())
  File "/home/eecs/shiry/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 2853, in contour
    ret = ax.contour(*args, **kwargs)
  File "/home/eecs/shiry/anaconda2/lib/python2.7/site-packages/matplotlib/__init__.py", line 1898, in inner
    return func(ax, *args, **kwargs)
  File "/home/eecs/shiry/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 5825, in contour
    contours = mcontour.QuadContourSet(self, *args, **kwargs)
  File "/home/eecs/shiry/anaconda2/lib/python2.7/site-packages/matplotlib/contour.py", line 865, in __init__
    self._process_levels()
  File "/home/eecs/shiry/anaconda2/lib/python2.7/site-packages/matplotlib/contour.py", line 1199, in _process_levels
    self.vmin = np.amin(self.levels)
  File "/home/eecs/shiry/anaconda2/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2352, in amin
    out=out, **kwargs)
  File "/home/eecs/shiry/anaconda2/lib/python2.7/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity

I am using the following commit of the pytorch master:

commit 329a2f7d27543ef21353c32b520980c666fa12cf
Author: Kai Arulkumaran <Kaixhin@users.noreply.github.com>
Date:   Sat Jun 17 16:13:03 2017 +0100

    Prevent divide by zero in dropout with p=1

Have you seen this behaviour before?
I was also seeing nans in gan_mnist before you added conv2d.

**Comment by caogang** [comment]
Maybe it is caused by this problem https://github.com/pytorch/pytorch/issues/1860. But I am not sure. You can update to the newest pytorch version to confirm whether it is solved.

Please tell me whether the bug exist after your test. Thanks.
