### ISSUE TITLE
Why can't I train a model by gan_mnist.py?

### ISSUE THREAD

**Issue by wlwsea** [caogang/wgan-gp#19]
When I use the command:   `python gan_mnist.py`
it shows the following error,   how can I solve this problem?
Thanks a ton!

`Traceback (most recent call last):
  File "gan_mnist.py", line 257, in <module>
    lib.plot.flush()
  File "/data2/wangjifeng/wgan-gp/tflib/plot.py", line 35, in flush
    plt.savefig(name.replace(' ', '_')+'.jpg')
  File "/root/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 697, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/matplotlib/figure.py", line 1573, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2252, in print_figure
    **kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 610, in print_jpg
    return background.save(filename_or_obj, format='jpeg', **options)
  File "/root/anaconda2/lib/python2.7/site-packages/PIL/Image.py", line 1672, in save
    fp = builtins.open(filename, "wb")
IOError: [Errno 2] No such file or directory: 'tmp/mnist/wasserstein_distance.jpg'
`

**Comment by caogang** [comment]
Oh, it is because that directory `tmp/mnist` is not exist. You can mkdir `tmp/mnist` in your directory and run the code. :)

**Comment by wlwsea** [comment]
It really works!  Thank you!
