### ISSUE TITLE
an error occurred

### ISSUE THREAD

**Issue by lzqcode** [caogang/wgan-gp#23]
Hello,when I run gan_cifar10.py, an error occurred: 
Traceback (most recent call last):
  File "gan_cifar10.py", line 187, in <module>
    _data = gen.next()
  File "gan_cifar10.py", line 170, in inf_train_gen
    for images, target in train_gen():
ValueError: too many values to unpack, I don't know how this mistake happened

**Comment by JunsongFan** [comment]
Just change this line (170) into:
for images in train_gen():

Also, line 258,
for images, _ in dev_gen():
should be changed into:
for images in dev_gen():
